### ISSUE TITLE
Managed database

### ISSUE THREAD

**Issue by A-Guldborg** [git-gurus-itu-devops/itu-minitwit#25]
Data must be wiped before simulator starts.
Allow ORM to define database and disregard `schema.sql` as we no longer rely on raw sql queries.

That is: Delete migration

**Comment by duckth** [comment]
Progress: Database has been created and code has been convereted.
Pipeline now needs to have any trace of SQLite (volume mounting etc.) removed

**Comment by A-Guldborg** [comment]
Issues with changing database:
- Sequence was not updated when we inserted data, causing issues when attempting to add more data (automatically setting id=1 when we already have data in the database). Solution: `ALTER SEQUENCE <name> RESTART WITH <latest id from table>`
- No vagrant up/provision/syncing of remote files, meaning our deploy script was not properly added to our VM. Solution: Manually altering `./minitwit/remotefiles/` through ssh
- Database migration from sqlite to psql failed due to being unable to handle all 101k messages in one transaction. Solution: Slicing by 1000 inserts at a time
