### ISSUE TITLE
Switch to minitwit domain

### ISSUE THREAD

**Issue by A-Guldborg** [git-gurus-itu-devops/itu-minitwit#33]
Includes:

- [ ] Fetch HTTPS certificate on deploying a new droplet ([Reference](https://docs.digitalocean.com/support/how-do-i-install-an-ssl-certificate-on-a-droplet/))
- [ ] Port forwarding or change port to 80 / 443 to avoid `:5000` in URL
- [ ] Setup api on `api.minitwit.tech` or similar, to hide API-port (not important)
- [ ] Make pull request for `repositories.py` in `lecture_notes` repository

**Comment by A-Guldborg** [comment]
Guides for setting up certificate:
Using [nginx](https://medium.com/@muaad/how-to-setup-a-letsencrypt-ssl-certificate-for-your-rails-app-on-nginx-fb2164b501a0)
[Newbie getting help for sinatrarb](https://community.letsencrypt.org/t/installing-ssl-on-simple-ruby-sinatra-web-app/132482/12)
[Certbot](https://certbot.eff.org/instructions?ws=webproduct&os=ubuntufocal)

Seems like our current droplet has `snapd` but might've been installed manually?
But we probably need to install that and certbot (`sudo snap install --classic certbot
`) in the vagrantfile through ssh, then run `sudo ln -s /snap/bin/certbot /usr/bin/certbot` and lastly `sudo certbot certonly --standalone` before deploying the container for minitwit. Might also require exposing port 80 somehow?

Might also have to expose ports 80/443 if that isn't done by default, or enable port forwarding somehow instead.

**Comment by fredpetersen** [comment]
Closed by nginx reverse proxy on swarm manager
